import i18n from '../i18n'
import { APP_CONFIG } from '../appConfig'
import { createState, encodedScore, step, STEP_MS, screenParticlePositions, CUT_MIN_Y, CUT_MAX_Y, type CutInput } from './engine.mjs'
import type { GameCallbacks, GameRuntime } from './types'

const W=390,H=844
const ko=()=>i18n.language.startsWith('ko')
export class CountergelGame implements GameRuntime {
 private canvas=document.createElement('canvas'); private ctx=this.canvas.getContext('2d')!; private state=createState()
 private cb:GameCallbacks|null=null; private raf=0; private last=0; private acc=0; private input?:CutInput
 private start?:{x:number,y:number}; private drag?:{x:number,y:number}; private slash?:{a:{x:number,y:number},b:{x:number,y:number},until:number}; private cueUntil=0
 private ro?:ResizeObserver; private audio?:AudioContext; private muted=false; private endedAt=0; private paused=false
 async mount(container:HTMLElement,callbacks:GameCallbacks){ this.cb=callbacks; this.canvas.width=W*2;this.canvas.height=H*2;this.ctx.scale(2,2);this.canvas.style.touchAction='none';container.append(this.canvas)
  this.canvas.setAttribute('role','application');this.updateLabel()
  const fit=()=>{const q=Math.min(container.clientWidth/W,container.clientHeight/H);this.canvas.style.width=`${W*q}px`;this.canvas.style.height=`${H*q}px`};fit();this.ro=new ResizeObserver(fit);this.ro.observe(container)
  this.canvas.addEventListener('pointerdown',this.down);this.canvas.addEventListener('pointermove',this.move);this.canvas.addEventListener('pointerup',this.up);this.canvas.addEventListener('pointercancel',this.cancel);window.addEventListener('keydown',this.key);document.addEventListener('visibilitychange',this.visibility)
  this.raf=requestAnimationFrame(this.loop)
 }
 private pos=(e:PointerEvent)=>{const r=this.canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
 private down=(e:PointerEvent)=>{e.preventDefault();this.unlock();this.canvas.setPointerCapture(e.pointerId);this.start=this.pos(e);this.drag=this.start}
 private move=(e:PointerEvent)=>{if(this.start){e.preventDefault();this.drag=this.pos(e)}}
 private cancel=(e:PointerEvent)=>{if(this.canvas.hasPointerCapture(e.pointerId))this.canvas.releasePointerCapture(e.pointerId);this.start=undefined;this.drag=undefined}
 private up=(e:PointerEvent)=>{e.preventDefault();const p=this.pos(e),a=this.start;this.start=undefined;this.drag=undefined;if(this.canvas.hasPointerCapture(e.pointerId))this.canvas.releasePointerCapture(e.pointerId);if(!a)return;this.slash={a,b:p,until:performance.now()+260};if(this.state.phase==='over'){if(performance.now()-this.endedAt>600&&p.y>650){this.cb?.onGameOver({score:encodedScore(this.state),phase:this.state.gel});this.restartRun()}return} const dx=p.x-a.x,dy=p.y-a.y;if(Math.hypot(dx,dy)<28){this.cueUntil=performance.now()+900;this.tone(180,.07);return}if(this.state.phase!=='falling'||this.state.y<CUT_MIN_Y||this.state.y>CUT_MAX_Y){this.cueUntil=performance.now()+900;this.tone(180,.07);return}this.input={x:((a.x+p.x)/2)/W,y:((a.y+p.y)/2)/H,angle:Math.atan2(dy,dx)};this.tone(540,.055)}
 private key=(e:KeyboardEvent)=>{if(e.key.toLowerCase()==='m'){this.muted=!this.muted;return} if(e.key==='Escape'){this.audio?.suspend();return} this.unlock();if(this.state.phase==='over'&&(e.key==='Enter'||e.key===' ')){if(performance.now()-this.endedAt>600){this.cb?.onGameOver({score:encodedScore(this.state),phase:this.state.gel});this.restartRun()}return} const y=this.state.y/H;if(e.key===' '||e.key==='Enter')this.input={x:.5,y,angle:Math.PI/2}; if(e.key==='ArrowLeft')this.input={x:.44,y,angle:Math.PI/2};if(e.key==='ArrowRight')this.input={x:.56,y,angle:Math.PI/2}}
 private visibility=()=>{if(document.hidden)this.audio?.suspend();else this.audio?.resume()}
 private unlock(){if(!this.audio)this.audio=new AudioContext();void this.audio.resume()}
 private tone(f:number,d:number){if(!this.audio||this.muted)return;const o=this.audio.createOscillator(),g=this.audio.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.05,this.audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,this.audio.currentTime+d);o.connect(g).connect(this.audio.destination);o.start();o.stop(this.audio.currentTime+d)}
 private loop=(now:number)=>{if(!this.last)this.last=now;if(!this.paused)this.acc+=Math.min(50,now-this.last);this.last=now;while(!this.paused&&this.acc>=STEP_MS){const before=this.state.serial;this.state=step(this.state,this.input);this.input=undefined;if(this.state.serial!==before)this.tone(this.state.lastJudgment==='miss'?120:this.state.lastJudgment==='perfect'?880:660,.16);if(this.state.phase==='over'&&!this.endedAt)this.endedAt=performance.now();this.acc-=STEP_MS}this.draw(now/1000);this.raf=requestAnimationFrame(this.loop)}
 private roundRect(x:number,y:number,w:number,h:number,r:number){this.ctx.beginPath();this.ctx.roundRect(x,y,w,h,r)}
 private text(s:string,x:number,y:number,size=16,align:CanvasTextAlign='center',color='#effffb'){const c=this.ctx;c.fillStyle=color;c.font=`bold ${size}px Galmuri11,monospace`;c.textAlign=align;c.fillText(s,x,y)}
 private gel(cx:number,y:number){const c=this.ctx,w=132,h=144;c.save();c.translate(cx,y);c.shadowColor='#dfff45';c.shadowBlur=22;const g=c.createLinearGradient(-w/2,0,w/2,h);g.addColorStop(0,'rgba(210,242,57,.68)');g.addColorStop(.5,'rgba(255,255,91,.9)');g.addColorStop(1,'rgba(142,213,43,.58)');c.fillStyle=g;this.roundRect(-w/2,-h/2,w,h,26);c.fill();c.shadowBlur=0;c.strokeStyle='rgba(240,255,194,.8)';c.lineWidth=3;c.stroke();for(const [i,p] of screenParticlePositions(this.state,W).entries()){const px=p.pixelX-cx,py=(p.y-.5)*h;c.fillStyle=p.kind==='seed'?'#162522':'rgba(255,255,255,.72)';c.beginPath();c.ellipse(px,py,p.kind==='seed'?4+p.weight:3,3,i*.7,0,Math.PI*2);c.fill();if(p.kind==='seed'&&p.weight>2){c.strokeStyle='#dfff3f';c.lineWidth=1;c.stroke()}}c.restore()}
 private splitGel(){const cut=this.state.cut;if(!cut)return;const c=this.ctx,total=this.state.lastJudgment==='perfect'?700:this.state.lastJudgment==='stable'?850:1050,p=Math.max(0,Math.min(1,1-this.state.settle/total)),ease=1-(1-p)**3;const startX=cut.gelX*W,startY=cut.gelY,targetY=620;const y=startY+(targetY-startY)*ease;const gap=12+42*Math.sin(Math.min(1,p*1.8)*Math.PI/2);const nx=-Math.sin(cut.angle),ny=Math.cos(cut.angle),cutX=cut.x*W,cutY=cut.y*H;for(const side of [-1,1]){c.save();const spreadX=side*(gap*nx+ease*48),spreadY=side*gap*ny*(1-ease*.45),turn=side*(.04+.14*ease);c.translate(spreadX,y-startY+spreadY);c.translate(startX,startY);c.rotate(turn);c.translate(-startX,-startY);c.beginPath();const span=1000,dx=Math.cos(cut.angle)*span,dy=Math.sin(cut.angle)*span;c.moveTo(cutX-dx,cutY-dy);c.lineTo(cutX+dx,cutY+dy);c.lineTo(cutX+dx+nx*span*side,cutY+dy+ny*span*side);c.lineTo(cutX-dx+nx*span*side,cutY-dy+ny*span*side);c.closePath();c.clip();this.gel(startX,startY);c.setLineDash([]);c.strokeStyle='#f4ffb8';c.shadowColor='#dfff45';c.shadowBlur=14;c.lineWidth=7;c.beginPath();c.moveTo(cutX-90*Math.cos(cut.angle),cutY-90*Math.sin(cut.angle));c.lineTo(cutX+90*Math.cos(cut.angle),cutY+90*Math.sin(cut.angle));c.stroke();c.restore()}c.save();c.strokeStyle=this.state.lastJudgment==='miss'?'#ff8d70':this.state.lastJudgment==='stable'?'#ffe36e':'#ffffff';c.shadowColor='#dfff45';c.shadowBlur=15;c.lineWidth=this.state.lastJudgment==='perfect'?5:3;c.setLineDash([9,5]);c.beginPath();const lineY=cutY+(y-startY);c.moveTo(cutX-75*Math.cos(cut.angle),lineY-75*Math.sin(cut.angle));c.lineTo(cutX+75*Math.cos(cut.angle),lineY+75*Math.sin(cut.angle));c.stroke();c.restore()}
 private draw(t:number){const c=this.ctx;c.clearRect(0,0,W,H);const bg=c.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#123d43');bg.addColorStop(1,'#07191e');c.fillStyle=bg;c.fillRect(0,0,W,H)
  c.strokeStyle='rgba(75,223,211,.22)';c.lineWidth=2;for(const x of [28,66,324,362]){c.beginPath();c.moveTo(x,0);c.lineTo(x,H);c.stroke()}
  this.text(`GEL ${Math.min(this.state.gel+1,12)}/12`,20,38,15,'left','#dfff45');this.text(`✕ ${this.state.misses}/3`,370,38,15,'right','#ff8d70');this.text(ko()?`밴드 ${this.state.band+1}`:`BAND ${this.state.band+1}`,195,38,13,'center','#79d9d3')
  const ready=this.state.phase==='falling'&&this.state.y>=CUT_MIN_Y&&this.state.y<=CUT_MAX_Y,pulse=.55+.25*Math.sin(t*8);c.fillStyle=ready?`rgba(223,255,69,${pulse*.15})`:'rgba(73,214,203,.035)';c.fillRect(58,CUT_MIN_Y,274,CUT_MAX_Y-CUT_MIN_Y);c.strokeStyle=ready?'#dfff45':'#49d6cb';c.lineWidth=ready?6:3;c.shadowColor=ready?'#dfff45':'transparent';c.shadowBlur=ready?18:0;c.strokeRect(58,CUT_MIN_Y,274,CUT_MAX_Y-CUT_MIN_Y);c.shadowBlur=0;for(const y of [CUT_MIN_Y,CUT_MAX_Y]){c.fillStyle=ready?'#dfff45':'#49d6cb';c.fillRect(45,y-3,26,6);c.fillRect(319,y-3,26,6)}
  if(this.state.phase==='falling')this.text(ready?(ko()?'지금 베세요!':'CUT NOW!'):(ko()?'빛나는 구간을 기다리세요':'WAIT FOR THE GLOW'),195,316,ready?22:13,'center',ready?'#dfff45':'#79d9d3')
  if(this.state.phase==='falling')this.gel(W*(.5+this.state.sway),this.state.y)
  else if(this.state.phase==='settling'){this.splitGel();const err=this.state.lastError,tilt=Math.max(-.16,Math.min(.16,err*1.8));c.save();c.translate(195,682);c.rotate(tilt);c.fillStyle='#07191e';c.fillRect(-125,0,250,9);c.fillRect(-7,0,14,40);c.restore();this.resultCard()}
  if(this.state.guide&&this.state.phase==='falling'){c.fillStyle='rgba(4,17,20,.84)';this.roundRect(66,598,258,116,16);c.fill();this.text(ko()?'손가락 선대로 젤이 두 조각 납니다':'YOUR SWIPE BECOMES THE REAL CUT',195,627,12);this.text(ko()?'빛날 때 무게 중심을 세로로 베기':'WHEN IT GLOWS · CUT VERTICALLY',195,653,12,'center','#dfff45');this.text(ko()?'12개 균형 · 3번 무너지면 종료':'BALANCE 12 · 3 COLLAPSES END',195,679,12,'center','#8fe4df');c.strokeStyle='#fff';c.lineWidth=4;c.beginPath();c.moveTo(195,548);c.lineTo(195,486);c.stroke();c.fillStyle='#fff';c.beginPath();c.arc(195,536-Math.sin(t*3)*20,8,0,Math.PI*2);c.fill()}
  if(this.state.phase==='over')this.overCard()
  const activeEnd=this.drag&&this.start?this.drag:null,activeStart=this.start;if(activeEnd&&activeStart)this.drawSlash(activeStart,activeEnd,.8);if(this.slash&&performance.now()<this.slash.until)this.drawSlash(this.slash.a,this.slash.b,(this.slash.until-performance.now())/220)
  if(performance.now()<this.cueUntil)this.text(ko()?'젤 전체가 빛날 때 길게 그으세요':'SWIPE WHEN THE WHOLE GEL GLOWS',195,744,12,'center','#ff8d70')
  this.text(this.muted?'MUTED · M':'SOUND · M',16,820,11,'left','#72aaa8')
 }
 private drawSlash(a:{x:number,y:number},b:{x:number,y:number},alpha:number){const c=this.ctx;c.save();c.globalAlpha=Math.max(0,Math.min(1,alpha));c.strokeStyle='#ffffff';c.shadowColor='#dfff45';c.shadowBlur=12;c.lineWidth=6;c.lineCap='round';c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.restore()}
 private resultCard(){const j=this.state.lastJudgment!,e=this.state.lastError,m=this.state.cut?.masses,total=(m?.[0]??0)+(m?.[1]??0),balance=total?`${(m![0]/total*100).toFixed(1)} : ${(m![1]/total*100).toFixed(1)}`:'—',dir=e>0?(ko()?'오른쪽이 무거움':'HEAVY RIGHT'):(ko()?'왼쪽이 무거움':'HEAVY LEFT');this.text(j==='perfect'?(ko()?'완벽한 균형':'PERFECT BALANCE'):j==='stable'?(ko()?'안정':'STABLE'):(ko()?'붕괴':'COLLAPSE'),195,746,22,'center',j==='miss'?'#ff8d70':j==='stable'?'#ffe36e':'#dfff45');this.text(j==='perfect'?balance:`${dir} · ${balance}`,195,773,12,'center','#b8e3df')}
 private overCard(){const c=this.ctx;c.fillStyle='rgba(3,13,16,.93)';c.fillRect(32,190,326,540);this.text(ko()?'실험 종료':'TRIAL OVER',195,258,31,'center','#ff8d70');this.text(`${this.state.gel}/12 · ${this.state.perfects} PERFECT`,195,306,15,'center','#dfff45');const weak=this.state.misses?Math.min(4,Math.ceil(this.state.gel/3)):'—';this.text(ko()?`가장 약한 밴드 ${weak}`:`WEAKEST BAND ${weak}`,195,344,13,'center','#8fe4df');c.fillStyle='#dfff45';this.roundRect(75,654,240,58,14);c.fill();this.text(ko()?'다시 베기':'CUT AGAIN',195,690,18,'center','#07191e')}
 setPaused(value:boolean){this.paused=value;if(value)void this.audio?.suspend();else void this.audio?.resume()}
 setMuted(value:boolean){this.muted=value}
 private updateLabel(){this.canvas.setAttribute('aria-label',ko()?'균형젤. 젤이 청록색 틀 안에 있을 때 무게 중심을 가로질러 한 번 그으세요.':'Countergel. Swipe once through the center of mass while the gel is inside the teal frame.')}
 setLocale(locale:'ko'|'en'){void i18n.changeLanguage(locale);this.updateLabel()}
 restartRun(){this.state=createState();this.input=undefined;this.endedAt=0;this.acc=0}
 destroy(){cancelAnimationFrame(this.raf);this.ro?.disconnect();this.canvas.removeEventListener('pointerdown',this.down);this.canvas.removeEventListener('pointermove',this.move);this.canvas.removeEventListener('pointerup',this.up);this.canvas.removeEventListener('pointercancel',this.cancel);window.removeEventListener('keydown',this.key);document.removeEventListener('visibilitychange',this.visibility);void this.audio?.close();this.canvas.remove()}
 getDebugState(){return{...this.state,over:this.state.phase==='over',score:encodedScore(this.state)}}
}
